⬆️ plugin: update intl to 0.19.0
aissat/easy_localization pull request #638
Opened 2023-12-26 03:31 UTC by tajjacob

upgrade intl to 0.19.0

#freepalestine
#stopgenocide
#ceasefirenow

2023-12-26 07:50 UTC, bw-flagship requested changes

2023-12-26 07:50 UTC, bw-flagship commented on .idea/.gitignore
> +# CodeStream ignored files
Remove this file please

2023-12-26 09:00 UTC, tajjacob commented on .idea/.gitignore
> +# CodeStream ignored files
done. please check again.

2023-12-26 10:41 UTC, bw-flagship approved these changes

2023-12-26 13:48 UTC, merged

2024-02-09 07:03 UTC, JgomesAT commented
any new about that merge??

2024-02-11 07:37 UTC, bw-flagship commented
It is released now in version 3.0.4

2024-02-13 07:03 UTC, JgomesAT commented
Your work is done, but need the same of FLutter:

Because easy_localization >=3.0.0-nullsafety depends on flutter_localizations from sdk which depends on intl 0.18.1, easy_localization >=3.0.0-nullsafety requires intl 0.18.1.