add multi-asset loader
aissat/easy_localization pull request #654
Opened 2024-02-28 20:08 UTC by hamed-rezaee

- Add multi-asset loader to add more than one asset loader if it is needed, for example, if you want to add package localization to your project.

2024-02-28 20:15 UTC, bw-flagship commented
Can you elaborate on a usecase? Why do you need multiple asset loaders for package localization?

2024-02-28 20:23 UTC, hamed-rezaee commented
> Can you elaborate on a usecase? Why do you need multiple asset loaders for package localization?

Hi @bw-flagship 

This discussion: https://github.com/aissat/easy_localization/discussions/592

and also here is another usecase:

https://stackoverflow.com/questions/78068216/how-can-i-add-a-localizationsdelegate-form-another-package-that-uses-easylocali

I have a package that uses the `EasyLocalization` package for localization, and I want to add `localizationsDelegate` of this package to my main project.

I know that I can add something like this with `flutter_intl` package to `pubspec.yaml`:

```yaml
flutter_intl:
  main_locale: en
  enabled: true
  class_name: MyPackageLocalization
```

And add the `MyPackageLocalization.delegate` to my `localizationsDelegates` inside the `MaterialApp`:

```dart
...
MaterialApp(
  localizationsDelegates: [
    ...context.localizationDelegates,
    MyPackageLocalization.delegate,
  ],
  supportedLocales: context.supportedLocales,
...
```

But, how can I do it with the `EasyLocalization` package?

2024-02-29 07:34 UTC, bw-flagship commented
@hamed-rezaee thanks for explaining!
I understand the purpose of the PR an since the discussion has at least a few upvotes, it seems to be a useful feature.

Some things prevent me from approving this pr in the current state:
- The breaking change seems unnecessary. You can optionally accept a single asset loader in the constructor and pass it to the list. In v4.0 we could make the breaking change then
- Instead of  `(await Future.wait(loaderFutures)).othermethods()`, I think `await Future.wait(loaderFutures).then((x) => othermethods())` would be more readable
- Let's avoid the dependency to collection if possible. Each dependency we introduce might cause problems for consumers of the library
- There seem to be unnecessary formatting changes which make the PR hard to review
- We need unittests for this new functionality and for the new util

2024-02-29 08:22 UTC, hamed-rezaee commented
> @hamed-rezaee thanks for explaining! I understand the purpose of the PR an since the discussion has at least a few upvotes, it seems to be a useful feature.
> 
> Some things prevent me from approving this pr in the current state:
> 
> * The breaking change seems unnecessary. You can optionally accept a single asset loader in the constructor and pass it to the list. In v4.0 we could make the breaking change then
> * Instead of  `(await Future.wait(loaderFutures)).othermethods()`, I think `await Future.wait(loaderFutures).then((x) => othermethods())` would be more readable
> * Let's avoid the dependency to collection if possible. Each dependency we introduce might cause problems for consumers of the library
> * There seem to be unnecessary formatting changes which make the PR hard to review
> * We need unittests for this new functionality and for the new util

@bw-flagship  I will apply the suggested changes and update the PR asap. 👍🏻

2024-02-29 20:43 UTC, hamed-rezaee commented
Hey @bw-flagship this PR is ready for review.

2024-03-01 07:56 UTC, bw-flagship requested changes
This looks very good! Some minor findings

2024-03-01 07:56 UTC, bw-flagship commented on lib/src/easy_localization_controller.dart
> +    final Locale desieredLocale =
Typo

2024-03-01 07:56 UTC, bw-flagship commented on lib/src/utils.dart
> +  void addAllRecursive(Map<K, dynamic> other) {
This is extension is never used, is it?

2024-03-01 07:56 UTC, bw-flagship commented on lib/src/easy_localization_controller.dart
> +          result.addAll(map);
maybe addAllRecursive needed here?

2024-03-01 12:13 UTC, bw-flagship approved these changes

2024-03-01 13:26 UTC, merged