add _supportedLocales in EasyLocalizationController; check the device…
aissat/easy_localization pull request #672
Opened 2024-05-01 06:02 UTC by bbsmartc

add _supportedLocales in EasyLocalizationController; check the deviceLocale in resetLocale; 
--
to fix this [issue](https://github.com/aissat/easy_localization/issues/670)

add scriptCode if useOnlyLangCode
--
scriptCode is needed sometimes, for example zh-Hans, zh-Hant

2024-05-01 07:38 UTC, bw-flagship requested changes

2024-05-01 07:38 UTC, bw-flagship commented on lib/src/easy_localization_controller.dart
>      EasyLocalization.logger('Reset locale to platform locale $_deviceLocale');
i would log locale instead of _deviceLocale here

2024-05-01 07:39 UTC, bw-flagship reviewed
oh and please add this to the changelog

2024-05-03 01:00 UTC, bbsmartc commented
changelog added

2024-05-03 01:00 UTC, bbsmartc commented
> oh and please add this to the changelog

changed added

2024-05-03 07:02 UTC, bw-flagship commented
@bbsmartc  did you see my other comment?

2024-05-03 07:33 UTC, bbsmartc commented
> @bbsmartc did you see my other comment?

sorry, forgot! in the latest pull request, the log is already modified to
```
    EasyLocalization.logger('Reset locale to $locale while the platform locale is $_deviceLocale and the fallback locale is $_fallbackLocale');

```

2024-05-03 07:34 UTC, bw-flagship approved these changes

2024-05-03 07:48 UTC, merged