fix strict countryCode problem
aissat/easy_localization pull request #690
Opened 2024-06-12 21:58 UTC by PatrickChrestin

Fix #674 

I added the functionality in that was described and discussed in the issue ticket.
I also added two tests based on the scenario mentioned in the issue ticket.

Feel free to comment or make suggestions.

@bw-flagship please have a look

2024-06-13 05:53 UTC, bw-flagship requested changes
Thanks for the PR! I like the change and the tests, there are just some formatting changes that need to be reverted

2024-06-13 05:53 UTC, bw-flagship commented on lib/src/easy_localization_controller.dart
> +    final locale = selectLocaleFrom(_supportedLocales!, deviceLocale,
unwanted changes here?

2024-06-13 05:53 UTC, bw-flagship commented on lib/src/easy_localization_controller.dart
> +    final Locale desiredLocale = useOnlyLangCode
unwanted changes here?

2024-06-13 05:53 UTC, bw-flagship commented on test/easy_localization_test.dart
> +          '',
unwanted changes here?

2024-06-13 06:21 UTC, PatrickChrestin commented
Perfect. I will take care of them when when I am back home from work.

2024-06-13 18:19 UTC, PatrickChrestin commented
The changes to formatting should be all resolved now.

2024-06-14 06:31 UTC, bw-flagship approved these changes

2024-06-14 06:50 UTC, merged